Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
# serilog section
Serilog:
  MinimumLevel: 
    Default: "Information"
  WriteTo:
    -
      Name: "Console"
    -
      Name: "File"
      Args: 
        path: "bin/lightning.webapi.log.txt"
        rollingInterval: "Day"  
# connection string section
ConnectionStrings:
  MSSql: ""